server:
  port: 9090

spring:
  # sql.init.mode means to run the predefined script when start app or not
  sql:
    init:
      mode: ALWAYS 
  config:
    activate:
      on-profile: production
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://productiondb:5432/bookdb}
    ## in case different credentials
    # username: ${SPRING_DATASOURCE_USERNAME:postgres}
    # password: ${SPRING_DATASOURCE_PASSWORD:123456}
  jpa:
    defer-datasource-initialization: false